#! /usr/bin/env python
"""Add Docstring here"""

# For testing purposes, remove later
from os import path
import sys
from matplotlib import pyplot as plt
import numpy as np


local = path.split(path.abspath(__file__))[0]

sys.path.insert(0,path.join(local, ".."))

bandMap = {"g" : 0,
           "r" : 1,
           "i" : 2,
           "z" : 3}

from intricate import template_tools

# Add restriction on RR type and forcefully apply lowercase

data_path = path.join(local, "..", "intricate", "data", "raw")
loadStuff = template_tools.template_stack("ab", data_path, "fourier_RRab_DECam.npz")
single_model = template_tools.single_template(loadStuff, 10891, bandMap["i"])
x = np.arange(0,1,0.01)
y1 = single_model.evaluate_in_phase(x)

loadStuff2 = template_tools.template_stack("ab", data_path, "fourier_RRab_DECam_new.npz")
single_model2 = template_tools.single_template(loadStuff2, 10891, bandMap["i"])
y2 = single_model2.evaluate_in_phase(x)

plt.plot(x,y1, label ="Dont ignore")
plt.plot(x,y2, label = "Ignore after N band")
plt.legend()
plt.gca().invert_yaxis()
plt.show()
# print(single_model.coefficients)
# print(single_model.n_terms)
# print(single_model.name)
# print(single_model.period)